# -*- coding: utf-8 -*-
"""Task 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nKIXV_huT6jsHswT0hBOROhcI1XVLypG
"""

def validate_name(name):
    if not name.strip():
        return False, "Name cannot be empty."

    if not name.replace(" ", "").isalpha():
        return False, "Name must contain only letters."

    return True, ""


def validate_marks(marks):
    if not marks.strip():
        return False, "Marks cannot be empty."

    if not marks.isdigit():
        return False, "Marks must be a number."

    marks = int(marks)

    if marks < 0 or marks > 100:
        return False, "Marks must be between 0 and 100."

    return True, ""


def calculate_grade(marks):
    if marks >= 90:
        return "A+"
    elif marks >= 80:
        return "A"
    elif marks >= 70:
        return "B"
    elif marks >= 60:
        return "C"
    elif marks >= 50:
        return "D"
    else:
        return "F"


def get_result(marks):
    if marks >= 50:
        return "PASS"
    else:
        return "FAIL"


def main():
    print("=" * 50)
    print("       STUDENT RESULT MANAGEMENT SYSTEM")
    print("=" * 50)

    name = input("\nEnter student name: ").strip()

    valid, error = validate_name(name)

    if not valid:
        print("\nError:", error)
        return

    marks_input = input("Enter marks (0-100): ").strip()

    valid, error = validate_marks(marks_input)

    if not valid:
        print("\nError:", error)
        return

    marks = int(marks_input)

    grade = calculate_grade(marks)
    result = get_result(marks)

    print("\n" + "=" * 50)
    print("             STUDENT RESULT")
    print("=" * 50)

    print("Student Name :", name)
    print("Marks        :", marks)
    print("Grade        :", grade)
    print("Result       :", result)

    print("=" * 50)
    print("Result generated successfully.")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nProgram stopped by user.")
    except Exception as error:
        print("\nUnexpected error:", error)