# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14c-JjHqOvHGo2DkZyH0UJq4Zo3UDKze6
"""

import requests

print("=" * 45)
print("   PUBLIC USER INFORMATION SYSTEM")
print("=" * 45)

user_id = input("\nEnter User ID (1-10): ").strip()

# Input validation
if not user_id.isdigit():
    print("\nError: Please enter a number from 1 to 10.")

else:
    user_id = int(user_id)

    if user_id < 1 or user_id > 10:
        print("\nError: User ID must be between 1 and 10.")

    else:
        try:
            url = "https://jsonplaceholder.typicode.com/users/" + str(user_id)

            response = requests.get(url, timeout=10)

            if response.status_code == 200:
                data = response.json()

                print("\n" + "=" * 45)
                print("           USER INFORMATION")
                print("=" * 45)

                print("Name     :", data["name"])
                print("Username :", data["username"])
                print("Email    :", data["email"])
                print("Phone    :", data["phone"])
                print("Website  :", data["website"])
                print("Company  :", data["company"]["name"])

                print("=" * 45)
                print("Data retrieved successfully.")

            else:
                print("\nError: User information not found.")

        except requests.exceptions.RequestException:
            print("\nError: Unable to connect to the public API.")

        except Exception as e:
            print("\nError:", e)